version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    
  - package-ecosystem: "nuget"
    directory: "./server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
