version: "3"

volumes:
  storage:

services:

  webserver:
    image: nginx:stable
    container_name: "Webserver"
    restart: unless-stopped
    environment:
      TZ: "Asia/Tehran"
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - frontend
      - backend

  redis:
    image: redis:7.0
    container_name: "Redis"
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./docker/redis/redis.conf:/usr/local/etc/redis.conf"
    environment:
      TZ: "Asia/Tehran"
    ports:
      - "6379:6379"

  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    image: shadowshare_front:0.0.0-alpha
    container_name: "Frontend"
    restart: unless-stopped
    environment:
      TZ: "Asia/Tehran"
      NODE_ENV: "production"
    depends_on:
      - backend

  backend:
    build:
      context: server
      dockerfile: ShadowShareAPI/Dockerfile
    image: shadowshare_api:0.0.0-alpha
    container_name: "API"
    restart: unless-stopped
    environment:
      TZ: "Asia/Tehran"
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "redis:6379"
      StorageLocation: "/mnt/storage"
    volumes:
      - "storage:/mnt/storage"
    depends_on:
      - redis

  cleaner:
    build:
      context: server
      dockerfile: CleanerService/Dockerfile
    image: shadowshare_cleaner:0.0.0-alpha
    container_name: "Cleaner"
    restart: unless-stopped
    environment:
      TZ: "Asia/Tehran"
      REDIS_CONNECTION_STRING: "redis:6379"
      STORAGE_LOCATION: "/mnt/storage"
    volumes:
      - "storage:/mnt/storage"
    depends_on:
      - redis